package contacttransmut;

import org.w3c.dom.Document;

/**
 *
 * @author ovečka
 */

/*
 * this is input filter.
 * it should have a constructor with parameters to set up options for loading the input file (see below)
 * output is facilitated by the two methods
 * output formats: Document (as "InternalDoc" produced by ReadCSV implementation)
 *                 InternalDocColumnSchema (there is already an implementation InternalDocColumnSchemaImpl)
 * If the read file is "dumb" (eg CSV), only Document is produced and getColumnSchema() returns NULL!
 * If the read file is already tagged (eg VCF), InternalDocColumnSchema should be generated by read() method and
 * returned by getColumnSchema() method!
 */
public interface InputFilter {
    //should allow to choose filename, encoding and filetype-specific parameters
    //Document format should be exactly the same as in ReadCSV implementation
    //If the loaded file has some schema information (what is phone, address, etc), then create non-blank InternalDocColumnSchema
     public Document read();

     //if no columnschema was read, should return null!
     public InternalDocColumnSchema getColumnSchema();

}
