/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactTransmutGUIMain.java
 *
 * Created on 30.4.2011, 13:48:29
 */

package gui;

import contacttransmut.InputFilter;
import contacttransmut.InternalDocColumnSchema;
import contacttransmut.ReadCSV;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author Martin
 */
public class ContactTransmutGUIMain extends javax.swing.JFrame {

            
    private File inputFile;
    private Document internalDoc = null;
    private InternalDocColumnSchema columnSchema = null;

    /** Creates new form ContactTransmutGUIMain */
    public ContactTransmutGUIMain() {
        initComponents();
        //setContentPane(jPanel1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainWindowFrame2 = new javax.swing.JFrame();
        jMainWindowPanel2 = new javax.swing.JPanel();
        jMainLabel2 = new javax.swing.JLabel();
        jNextButton2 = new javax.swing.JButton();
        jCancelButton2 = new javax.swing.JButton();
        jBackButton2 = new javax.swing.JButton();
        jShowTextFileButton2 = new javax.swing.JButton();
        jShowInternalDocButton2 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jOriginalFileTextFrame = new javax.swing.JFrame();
        jOriginalFileScrollPane = new javax.swing.JScrollPane();
        jOriginalFileTextArea = new javax.swing.JTextArea();
        jInternalDocTextFrame = new javax.swing.JFrame();
        jInternalDocScrollPane = new javax.swing.JScrollPane();
        jInternalDocTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jMainLabel1 = new javax.swing.JLabel();
        jBrowseButton1 = new javax.swing.JButton();
        jInputFileTextField1 = new javax.swing.JTextField();
        jSelectInputLabel1 = new javax.swing.JLabel();
        jNextButton1 = new javax.swing.JButton();
        jCancelButton1 = new javax.swing.JButton();
        jBackButton1 = new javax.swing.JButton();

        jMainWindowFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jMainWindowFrame2.setTitle("Contact Transmutator 1.0");
        jMainWindowFrame2.setMinimumSize(new java.awt.Dimension(100, 100));

        jMainLabel2.setFont(new java.awt.Font("Chiller", 1, 48));
        jMainLabel2.setText("Contact Transmutator 1.0");

        jNextButton2.setText("Next >");
        jNextButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextButton2MouseReleased(evt);
            }
        });

        jCancelButton2.setText("Cancel");
        jCancelButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCancelButton2MouseReleased(evt);
            }
        });

        jBackButton2.setText("< Back");
        jBackButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBackButton2MouseReleased(evt);
            }
        });

        jShowTextFileButton2.setText("Show text");
        jShowTextFileButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowTextFileButton2MouseReleased(evt);
            }
        });

        jShowInternalDocButton2.setText("Show Internal Doc");
        jShowInternalDocButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowInternalDocButton2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jMainWindowPanel2Layout = new javax.swing.GroupLayout(jMainWindowPanel2);
        jMainWindowPanel2.setLayout(jMainWindowPanel2Layout);
        jMainWindowPanel2Layout.setHorizontalGroup(
            jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jMainLabel2)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainWindowPanel2Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jShowInternalDocButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowTextFileButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBackButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNextButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton2)
                .addContainerGap())
        );
        jMainWindowPanel2Layout.setVerticalGroup(
            jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addGroup(jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNextButton2)
                        .addComponent(jBackButton2)
                        .addComponent(jShowTextFileButton2)
                        .addComponent(jShowInternalDocButton2))
                    .addComponent(jCancelButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jMainWindowFrame2Layout = new javax.swing.GroupLayout(jMainWindowFrame2.getContentPane());
        jMainWindowFrame2.getContentPane().setLayout(jMainWindowFrame2Layout);
        jMainWindowFrame2Layout.setHorizontalGroup(
            jMainWindowFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainWindowPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMainWindowFrame2Layout.setVerticalGroup(
            jMainWindowFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainWindowPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jOriginalFileTextArea.setColumns(20);
        jOriginalFileTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jOriginalFileTextArea.setRows(5);
        jOriginalFileScrollPane.setViewportView(jOriginalFileTextArea);

        javax.swing.GroupLayout jOriginalFileTextFrameLayout = new javax.swing.GroupLayout(jOriginalFileTextFrame.getContentPane());
        jOriginalFileTextFrame.getContentPane().setLayout(jOriginalFileTextFrameLayout);
        jOriginalFileTextFrameLayout.setHorizontalGroup(
            jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOriginalFileTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jOriginalFileScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jOriginalFileTextFrameLayout.setVerticalGroup(
            jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jOriginalFileTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jOriginalFileScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jInternalDocTextFrame.setTitle("InternalDoc");

        jInternalDocTextArea.setColumns(20);
        jInternalDocTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jInternalDocTextArea.setRows(5);
        jInternalDocScrollPane.setViewportView(jInternalDocTextArea);

        javax.swing.GroupLayout jInternalDocTextFrameLayout = new javax.swing.GroupLayout(jInternalDocTextFrame.getContentPane());
        jInternalDocTextFrame.getContentPane().setLayout(jInternalDocTextFrameLayout);
        jInternalDocTextFrameLayout.setHorizontalGroup(
            jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalDocTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jInternalDocScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jInternalDocTextFrameLayout.setVerticalGroup(
            jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalDocTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jInternalDocScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Transmutator 1.0");
        setResizable(false);

        jMainLabel1.setFont(new java.awt.Font("Chiller", 1, 48));
        jMainLabel1.setText("Contact Transmutator 1.0");

        jBrowseButton1.setText("Browse...");
        jBrowseButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBrowseButton1MouseReleased(evt);
            }
        });

        jSelectInputLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jSelectInputLabel1.setText("Please select the input file:");

        jNextButton1.setText("Next >");
        jNextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextButton1MouseReleased(evt);
            }
        });

        jCancelButton1.setText("Cancel");
        jCancelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCancelButton1MouseReleased(evt);
            }
        });

        jBackButton1.setText("< Back");
        jBackButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jInputFileTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBrowseButton1)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jMainLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSelectInputLabel1)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jBackButton1)
                .addGap(4, 4, 4)
                .addComponent(jNextButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainLabel1)
                .addGap(30, 30, 30)
                .addComponent(jSelectInputLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBrowseButton1)
                    .addComponent(jInputFileTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBackButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCancelButton1)
                        .addComponent(jNextButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNextButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextButton1MouseReleased

        //TODO: statusbar

        String filePath = jInputFileTextField1.getText();

        // <editor-fold defaultstate="collapsed" desc="naplnenie InternalDoc a ColumnSchema">
        InputFilter inputFilter;
        //TODO: detect encoding
        if (filePath.toLowerCase().endsWith(".csv")){
            inputFilter = new ReadCSV(inputFile.toString(),"UTF-8",",","\"");
            internalDoc = inputFilter.read();
            columnSchema = inputFilter.getColumnSchema();
        } else if (filePath.toLowerCase().endsWith(".csv")){
            JOptionPane.showMessageDialog(this,"File type not supported yet.","Sorry!",JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (filePath.toLowerCase().endsWith(".csv")){
            JOptionPane.showMessageDialog(this,"File type not supported yet.","Sorry!",JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(this,"Choose a valid file. (*.csv, *.ods, *.vcf)","Invalid file path!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //</editor-fold>
       
        // <editor-fold defaultstate="collapsed" desc="nacitanie do Show Original Text">
        String line = null;
        BufferedReader buff = null;
        try{
            inputFile = new File(filePath);
            buff = new BufferedReader(
                       new InputStreamReader(
                           new FileInputStream(
                               inputFile)));

            jOriginalFileTextArea.setText(null);
            while ((line = buff.readLine()) != null){
                jOriginalFileTextArea.append(line + "\n");
            }
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(this,"The file specified was not found. Check the file path!","File not found!",JOptionPane.ERROR_MESSAGE);
            return;
        } catch(IOException ex){
            JOptionPane.showMessageDialog(this,"An error occured. Please try again.","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        } finally {
            try {
                if(buff != null) {buff.close();}
            } catch(IOException ex){
                JOptionPane.showMessageDialog(this,"An error occured. Please try again.","Error!",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        // </editor-fold>

        // <editor-fold defaultstate="collapsed" desc="nacitanie do Show Internal Doc">
        if (internalDoc == null){
            jInternalDocTextArea.setText("Document is null!!!");
        } else {
            jInternalDocTextArea.append("<root>" + System.getProperty("line.separator"));
            NodeList contactList = internalDoc.getElementsByTagName("contact");
            for (int i=0; i<contactList.getLength(); i++){
                jInternalDocTextArea.append("    <contact>" + System.getProperty("line.separator"));
                Element contact = (Element) contactList.item(i);
                NodeList uncategorizedList = contact.getElementsByTagName("uncategorized");
                for (int j = 0; j<uncategorizedList.getLength(); j++){
                    jInternalDocTextArea.append("        <uncategorized>" + System.getProperty("line.separator"));
                    Element uncategorized = (Element) uncategorizedList.item(j);
                    NodeList dataList = uncategorized.getElementsByTagName("data");
                    for (int k = 0; k<dataList.getLength(); k++){
                        jInternalDocTextArea.append("            <data>");
                        jInternalDocTextArea.append(dataList.item(k).getTextContent());
                        jInternalDocTextArea.append("</data>" + System.getProperty("line.separator"));
                    }
                    jInternalDocTextArea.append("        </uncategorized>" + System.getProperty("line.separator"));
                }
                jInternalDocTextArea.append("    </contact>" + System.getProperty("line.separator"));
            }
            jInternalDocTextArea.append("</root>" + System.getProperty("line.separator"));
        }
        // </editor-fold>

        setVisible(false);
        jMainWindowFrame2.pack();
        jMainWindowFrame2.setVisible(true);
    }//GEN-LAST:event_jNextButton1MouseReleased

    private void jBrowseButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBrowseButton1MouseReleased
        JFileChooser chooser = new JFileChooser();

        // <editor-fold defaultstate="collapsed" desc="filter typov suborov">
        FileFilter filter = new FileFilter() {
            @Override
            public boolean accept(File f) {
                if ((f.isFile() && (f.toString().toLowerCase().endsWith("csv")
                                    || f.toString().toLowerCase().endsWith("ods")
                                    || f.toString().toLowerCase().endsWith("vcf")
                                    )
                     )
                     || f.isDirectory()) {
                    return true;
                } else {
                    return false;
                }
            }
            @Override
            public String getDescription() {
                return "CSV, ODS, VCF files";
            }
        };
        // </editor-fold>
              
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(jPanel1);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            jInputFileTextField1.setText(chooser.getSelectedFile().toString());
        }       
    }//GEN-LAST:event_jBrowseButton1MouseReleased

    private void jNextButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextButton2MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_jNextButton2MouseReleased

    private void jBackButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackButton2MouseReleased
        jMainWindowFrame2.setVisible(false);
        jOriginalFileTextFrame.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jBackButton2MouseReleased

    private void jCancelButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelButton1MouseReleased
        System.exit(0);
    }//GEN-LAST:event_jCancelButton1MouseReleased

    private void jCancelButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelButton2MouseReleased
        System.exit(0);
    }//GEN-LAST:event_jCancelButton2MouseReleased

    private void jShowTextFileButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowTextFileButton2MouseReleased
        jOriginalFileTextFrame.setTitle(inputFile.getName());
        jOriginalFileTextFrame.pack();
        jOriginalFileTextFrame.setVisible(true);
    }//GEN-LAST:event_jShowTextFileButton2MouseReleased

    private void jShowInternalDocButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowInternalDocButton2MouseReleased
        jInternalDocTextFrame.pack();
        jInternalDocTextFrame.setVisible(true);
    }//GEN-LAST:event_jShowInternalDocButton2MouseReleased


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactTransmutGUIMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton1;
    private javax.swing.JButton jBackButton2;
    private javax.swing.JButton jBrowseButton1;
    private javax.swing.JButton jCancelButton1;
    private javax.swing.JButton jCancelButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTextField jInputFileTextField1;
    private javax.swing.JScrollPane jInternalDocScrollPane;
    private javax.swing.JTextArea jInternalDocTextArea;
    private javax.swing.JFrame jInternalDocTextFrame;
    private javax.swing.JLabel jMainLabel1;
    private javax.swing.JLabel jMainLabel2;
    private javax.swing.JFrame jMainWindowFrame2;
    private javax.swing.JPanel jMainWindowPanel2;
    private javax.swing.JButton jNextButton1;
    private javax.swing.JButton jNextButton2;
    private javax.swing.JScrollPane jOriginalFileScrollPane;
    private javax.swing.JTextArea jOriginalFileTextArea;
    private javax.swing.JFrame jOriginalFileTextFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSelectInputLabel1;
    private javax.swing.JButton jShowInternalDocButton2;
    private javax.swing.JButton jShowTextFileButton2;
    // End of variables declaration//GEN-END:variables

}
