/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactTransmutGUIMain.java
 *
 * Created on 30.4.2011, 13:48:29
 */

package gui;

import contacttransmut.InputFilter;
import contacttransmut.InternalDocColumnSchema;
import contacttransmut.ReadCSV;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author Martin
 */
public class ContactTransmutGUIMain extends javax.swing.JFrame {

            
    private File inputFile;
    private Document internalDoc = null;
    private InternalDocColumnSchema columnSchema = null;
    private ContactsListTableModel tableModel = new ContactsListTableModel();

    /** Creates new form ContactTransmutGUIMain */
    public ContactTransmutGUIMain() {
        initComponents();

        jContactsListTable2.setModel(tableModel);
        jContactsListTable2.setAutoscrolls(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainWindowFrame2 = new javax.swing.JFrame();
        jMainWindowPanel2 = new javax.swing.JPanel();
        jMainLabel2 = new javax.swing.JLabel();
        jNextButton2 = new javax.swing.JButton();
        jCancelButton2 = new javax.swing.JButton();
        jBackButton2 = new javax.swing.JButton();
        jShowTextFileButton2 = new javax.swing.JButton();
        jShowInternalDocButton2 = new javax.swing.JButton();
        jContactsListScrollPane2 = new javax.swing.JScrollPane();
        jContactsListTable2 = new javax.swing.JTable();
        jShowColumnSchemaButton2 = new javax.swing.JButton();
        jTestTextField1 = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jOriginalFileTextFrame = new javax.swing.JFrame();
        jOriginalFileScrollPane = new javax.swing.JScrollPane();
        jOriginalFileTextArea = new javax.swing.JTextArea();
        jInternalDocTextFrame = new javax.swing.JFrame();
        jInternalDocScrollPane = new javax.swing.JScrollPane();
        jInternalDocTextArea = new javax.swing.JTextArea();
        jColumnSchemaTextFrame = new javax.swing.JFrame();
        jColumnSchemaScrollPane = new javax.swing.JScrollPane();
        jColumnSchemaTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jMainLabel1 = new javax.swing.JLabel();
        jBrowseButton1 = new javax.swing.JButton();
        jInputFileTextField1 = new javax.swing.JTextField();
        jSelectInputLabel1 = new javax.swing.JLabel();
        jNextButton1 = new javax.swing.JButton();
        jCancelButton1 = new javax.swing.JButton();
        jBackButton1 = new javax.swing.JButton();

        jMainWindowFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jMainWindowFrame2.setTitle("Contact Transmutator 1.0");
        jMainWindowFrame2.setMinimumSize(new java.awt.Dimension(100, 100));

        jMainLabel2.setFont(new java.awt.Font("Chiller", 1, 48));
        jMainLabel2.setText("Contact Transmutator 1.0");

        jNextButton2.setText("Next >");
        jNextButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextButton2MouseReleased(evt);
            }
        });

        jCancelButton2.setText("Cancel");
        jCancelButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCancelButton2MouseReleased(evt);
            }
        });

        jBackButton2.setText("< Back");
        jBackButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBackButton2MouseReleased(evt);
            }
        });

        jShowTextFileButton2.setText("Show text");
        jShowTextFileButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowTextFileButton2MouseReleased(evt);
            }
        });

        jShowInternalDocButton2.setText("Show Internal Doc");
        jShowInternalDocButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowInternalDocButton2MouseReleased(evt);
            }
        });

        jContactsListTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jContactsListTable2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jContactsListTable2.setMinimumSize(new java.awt.Dimension(10, 10));
        jContactsListScrollPane2.setViewportView(jContactsListTable2);

        jShowColumnSchemaButton2.setText("Show Column Schema");
        jShowColumnSchemaButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowColumnSchemaButton2MouseReleased(evt);
            }
        });

        jTestTextField1.setText("default");

        javax.swing.GroupLayout jMainWindowPanel2Layout = new javax.swing.GroupLayout(jMainWindowPanel2);
        jMainWindowPanel2.setLayout(jMainWindowPanel2Layout);
        jMainWindowPanel2Layout.setHorizontalGroup(
            jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainWindowPanel2Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(jShowColumnSchemaButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowInternalDocButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowTextFileButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBackButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNextButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton2)
                .addContainerGap())
            .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jMainLabel2)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                        .addComponent(jTestTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jMainWindowPanel2Layout.createSequentialGroup()
                        .addComponent(jContactsListScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jMainWindowPanel2Layout.setVerticalGroup(
            jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainWindowPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainLabel2)
                .addGap(9, 9, 9)
                .addComponent(jTestTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jContactsListScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jMainWindowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNextButton2)
                        .addComponent(jBackButton2)
                        .addComponent(jShowTextFileButton2)
                        .addComponent(jShowInternalDocButton2)
                        .addComponent(jShowColumnSchemaButton2))
                    .addComponent(jCancelButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jMainWindowFrame2Layout = new javax.swing.GroupLayout(jMainWindowFrame2.getContentPane());
        jMainWindowFrame2.getContentPane().setLayout(jMainWindowFrame2Layout);
        jMainWindowFrame2Layout.setHorizontalGroup(
            jMainWindowFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainWindowPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jMainWindowFrame2Layout.setVerticalGroup(
            jMainWindowFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainWindowPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jOriginalFileTextArea.setColumns(20);
        jOriginalFileTextArea.setFont(new java.awt.Font("Arial", 0, 12));
        jOriginalFileTextArea.setRows(5);
        jOriginalFileScrollPane.setViewportView(jOriginalFileTextArea);

        javax.swing.GroupLayout jOriginalFileTextFrameLayout = new javax.swing.GroupLayout(jOriginalFileTextFrame.getContentPane());
        jOriginalFileTextFrame.getContentPane().setLayout(jOriginalFileTextFrameLayout);
        jOriginalFileTextFrameLayout.setHorizontalGroup(
            jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOriginalFileTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jOriginalFileScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jOriginalFileTextFrameLayout.setVerticalGroup(
            jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jOriginalFileTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jOriginalFileTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jOriginalFileScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jInternalDocTextFrame.setTitle("InternalDoc");

        jInternalDocTextArea.setColumns(20);
        jInternalDocTextArea.setFont(new java.awt.Font("Arial", 0, 12));
        jInternalDocTextArea.setRows(5);
        jInternalDocScrollPane.setViewportView(jInternalDocTextArea);

        javax.swing.GroupLayout jInternalDocTextFrameLayout = new javax.swing.GroupLayout(jInternalDocTextFrame.getContentPane());
        jInternalDocTextFrame.getContentPane().setLayout(jInternalDocTextFrameLayout);
        jInternalDocTextFrameLayout.setHorizontalGroup(
            jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalDocTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jInternalDocScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jInternalDocTextFrameLayout.setVerticalGroup(
            jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jInternalDocTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalDocTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jInternalDocScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jColumnSchemaTextArea.setColumns(20);
        jColumnSchemaTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jColumnSchemaTextArea.setRows(5);
        jColumnSchemaScrollPane.setViewportView(jColumnSchemaTextArea);

        javax.swing.GroupLayout jColumnSchemaTextFrameLayout = new javax.swing.GroupLayout(jColumnSchemaTextFrame.getContentPane());
        jColumnSchemaTextFrame.getContentPane().setLayout(jColumnSchemaTextFrameLayout);
        jColumnSchemaTextFrameLayout.setHorizontalGroup(
            jColumnSchemaTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jColumnSchemaTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jColumnSchemaTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jColumnSchemaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jColumnSchemaTextFrameLayout.setVerticalGroup(
            jColumnSchemaTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jColumnSchemaTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jColumnSchemaTextFrameLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jColumnSchemaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Transmutator 1.0");
        setResizable(false);

        jMainLabel1.setFont(new java.awt.Font("Chiller", 1, 48));
        jMainLabel1.setText("Contact Transmutator 1.0");

        jBrowseButton1.setText("Browse...");
        jBrowseButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBrowseButton1MouseReleased(evt);
            }
        });

        jSelectInputLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jSelectInputLabel1.setText("Please select the input file:");

        jNextButton1.setText("Next >");
        jNextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextButton1MouseReleased(evt);
            }
        });

        jCancelButton1.setText("Cancel");
        jCancelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCancelButton1MouseReleased(evt);
            }
        });

        jBackButton1.setText("< Back");
        jBackButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jInputFileTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBrowseButton1)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jMainLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSelectInputLabel1)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jBackButton1)
                .addGap(4, 4, 4)
                .addComponent(jNextButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainLabel1)
                .addGap(30, 30, 30)
                .addComponent(jSelectInputLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBrowseButton1)
                    .addComponent(jInputFileTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBackButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCancelButton1)
                        .addComponent(jNextButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNextButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextButton1MouseReleased

        //TODO: statusbar

        String filePath = jInputFileTextField1.getText();

        // <editor-fold defaultstate="collapsed" desc="naplnenie InternalDoc a ColumnSchema">
        InputFilter inputFilter;
        inputFile = new File(filePath);
        //TODO: detect encoding
        if (filePath.toLowerCase().endsWith(".csv")){
            inputFilter = new ReadCSV(inputFile.toString(),"UTF-8",",","\"");
            internalDoc = inputFilter.read();
            columnSchema = inputFilter.getColumnSchema();
        } else if (filePath.toLowerCase().endsWith(".vcf")){
            JOptionPane.showMessageDialog(this,"File type not supported yet.","Sorry!",JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (filePath.toLowerCase().endsWith(".osd")){
            JOptionPane.showMessageDialog(this,"File type not supported yet.","Sorry!",JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(this,"Choose a valid file. (*.csv, *.ods, *.vcf)","Invalid file path!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //</editor-fold>
       
        tableModel.initTable(internalDoc, columnSchema);

        jTestTextField1.setText(String.valueOf(tableModel.getColumnCount()) + ", " + String.valueOf(jContactsListTable2.getColumnCount()));

        setVisible(false);
        jMainWindowFrame2.pack();
        jMainWindowFrame2.setVisible(true);
        jMainWindowFrame2.repaint();
    }//GEN-LAST:event_jNextButton1MouseReleased

    private void jBrowseButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBrowseButton1MouseReleased
        JFileChooser chooser = new JFileChooser();

        // <editor-fold defaultstate="collapsed" desc="filter typov suborov">
        FileFilter filter = new FileFilter() {
            @Override
            public boolean accept(File f) {
                if ((f.isFile() && (f.toString().toLowerCase().endsWith("csv")
                                    || f.toString().toLowerCase().endsWith("ods")
                                    || f.toString().toLowerCase().endsWith("vcf")
                                    )
                     )
                     || f.isDirectory()) {
                    return true;
                } else {
                    return false;
                }
            }
            @Override
            public String getDescription() {
                return "CSV, ODS, VCF files";
            }
        };
        // </editor-fold>
              
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(jPanel1);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            jInputFileTextField1.setText(chooser.getSelectedFile().toString());
        }       
    }//GEN-LAST:event_jBrowseButton1MouseReleased

    private void jNextButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextButton2MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_jNextButton2MouseReleased

    private void jBackButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackButton2MouseReleased
        jMainWindowFrame2.setVisible(false);
        jOriginalFileTextFrame.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jBackButton2MouseReleased

    private void jCancelButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelButton1MouseReleased
        System.exit(0);
    }//GEN-LAST:event_jCancelButton1MouseReleased

    private void jCancelButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelButton2MouseReleased
        System.exit(0);
    }//GEN-LAST:event_jCancelButton2MouseReleased

    private void jShowTextFileButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowTextFileButton2MouseReleased

        if (jOriginalFileTextFrame.isVisible()) {
            jOriginalFileTextFrame.requestFocus();
        } else {
            // <editor-fold defaultstate="collapsed" desc="nacitanie do Show Original Text">
            String line = null;
            BufferedReader buff = null;
            try {
                buff = new BufferedReader(
                        new InputStreamReader(
                        new FileInputStream(
                        inputFile)));

                jOriginalFileTextArea.setText(null);
                while ((line = buff.readLine()) != null) {
                    jOriginalFileTextArea.append(line + "\n");
                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "The file specified was not found. Check the file path!", "File not found!", JOptionPane.ERROR_MESSAGE);
                return;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "An error occured. Please try again.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } finally {
                try {
                    if (buff != null) {
                        buff.close();
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "An error occured. Please try again.", "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // </editor-fold>
            jOriginalFileTextFrame.setTitle(inputFile.getName());
            jOriginalFileTextFrame.pack();
            jOriginalFileTextFrame.setVisible(true);
        }
    }//GEN-LAST:event_jShowTextFileButton2MouseReleased

    private void jShowInternalDocButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowInternalDocButton2MouseReleased

        if (jInternalDocTextFrame.isVisible()) {
            jInternalDocTextFrame.requestFocus();
        } else {

            internalDoc = tableModel.getInternalDoc();

            // <editor-fold defaultstate="collapsed" desc="nacitanie do Show Internal Doc">
            if (internalDoc == null) {
                jInternalDocTextArea.setText("Document is null!!!");
            } else {
                jInternalDocTextArea.setText("<root>" + System.getProperty("line.separator"));
                NodeList contactList = internalDoc.getElementsByTagName("contact");
                for (int i = 0; i < contactList.getLength(); i++) {
                    jInternalDocTextArea.append("    <contact>" + System.getProperty("line.separator"));
                    Element contact = (Element) contactList.item(i);
                    NodeList uncategorizedList = contact.getElementsByTagName("uncategorized");
                    for (int j = 0; j < uncategorizedList.getLength(); j++) {
                        jInternalDocTextArea.append("        <uncategorized>" + System.getProperty("line.separator"));
                        Element uncategorized = (Element) uncategorizedList.item(j);
                        NodeList dataList = uncategorized.getElementsByTagName("data");
                        for (int k = 0; k < dataList.getLength(); k++) {
                            jInternalDocTextArea.append("            <data>");
                            jInternalDocTextArea.append(dataList.item(k).getTextContent());
                            jInternalDocTextArea.append("</data>" + System.getProperty("line.separator"));
                        }
                        jInternalDocTextArea.append("        </uncategorized>" + System.getProperty("line.separator"));
                    }
                    jInternalDocTextArea.append("    </contact>" + System.getProperty("line.separator"));
                }
                jInternalDocTextArea.append("</root>" + System.getProperty("line.separator"));
            }
            // </editor-fold>

            jInternalDocTextFrame.pack();
            jInternalDocTextFrame.setVisible(true);
        }
    }//GEN-LAST:event_jShowInternalDocButton2MouseReleased

    private void jShowColumnSchemaButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowColumnSchemaButton2MouseReleased

        if (jColumnSchemaTextFrame.isVisible()) {
            jColumnSchemaTextFrame.requestFocus();
        } else {

            columnSchema = tableModel.getColumnSchema();

            jColumnSchemaTextArea.setText(columnSchema.toString());

            jColumnSchemaTextFrame.pack();
            jColumnSchemaTextFrame.setVisible(true);
        }
    }//GEN-LAST:event_jShowColumnSchemaButton2MouseReleased


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactTransmutGUIMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton1;
    private javax.swing.JButton jBackButton2;
    private javax.swing.JButton jBrowseButton1;
    private javax.swing.JButton jCancelButton1;
    private javax.swing.JButton jCancelButton2;
    private javax.swing.JScrollPane jColumnSchemaScrollPane;
    private javax.swing.JTextArea jColumnSchemaTextArea;
    private javax.swing.JFrame jColumnSchemaTextFrame;
    private javax.swing.JScrollPane jContactsListScrollPane2;
    private javax.swing.JTable jContactsListTable2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTextField jInputFileTextField1;
    private javax.swing.JScrollPane jInternalDocScrollPane;
    private javax.swing.JTextArea jInternalDocTextArea;
    private javax.swing.JFrame jInternalDocTextFrame;
    private javax.swing.JLabel jMainLabel1;
    private javax.swing.JLabel jMainLabel2;
    private javax.swing.JFrame jMainWindowFrame2;
    private javax.swing.JPanel jMainWindowPanel2;
    private javax.swing.JButton jNextButton1;
    private javax.swing.JButton jNextButton2;
    private javax.swing.JScrollPane jOriginalFileScrollPane;
    private javax.swing.JTextArea jOriginalFileTextArea;
    private javax.swing.JFrame jOriginalFileTextFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSelectInputLabel1;
    private javax.swing.JButton jShowColumnSchemaButton2;
    private javax.swing.JButton jShowInternalDocButton2;
    private javax.swing.JButton jShowTextFileButton2;
    private javax.swing.JTextField jTestTextField1;
    // End of variables declaration//GEN-END:variables

}
